# Generated by Django 4.1.5 on 2023-02-10 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('customer_ID', models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(unique=True)),
                ('account_balance', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
                ('account_type', models.CharField(max_length=30)),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicbankserver.customers')),
            ],
        ),
    ]
