# Generated by Django 4.1.5 on 2023-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicbankserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
