# Generated by Django 4.1.5 on 2023-01-30 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicbankserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_balance',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
    ]
