# Generated by Django 4.1.5 on 2023-02-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicbankserver', '0002_alter_accounts_account_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('customer_ID', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='account_name',
            new_name='account_type',
        ),
        migrations.AddField(
            model_name='accounts',
            name='customer_ID',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='basicbankserver.customers'),
        ),
    ]
